<<<<<<< HEAD
[general]
rtpstart=10000
rtpend=10200
icesupport=yes
=======
[general]
rtpstart=16384
rtpend=16484
icesupport=yes
>>>>>>> ee30bdb6c5f2cbe0463f79bd52b5fc80b53677c2
stunaddr=stun.l.google.com:19302 