<<<<<<< HEAD
[general]
sipdebug=yes
context=default
udpbindaddr=0.0.0.0
tcpenable=no
transport=udp
nat=force_rport,comedia
; Docker host network
localnet=192.168.65.0/24
externip=192.168.65.1
; Docker network
localnet=192.168.65.0/24
; Your external IP 
; You can use your external IP here  
externip=192.168.1.5   



;bindaddr=0.0.0.0
;udpbindaddr=0.0.0.0

;bindport=5060
;bindaddr=0.0.0.0
;nat=yes
;externip=${ASTERISK_IPADDR}
;localnet=192.168.1.0/255.255.255.0
;localnet=192.168.161.0/255.255.255.0
;allowguest=no
;alwaysauthreject=yes
;disallow=all
;allow=ulaw
;allow=alaw
;
;; RTP Configuration
;rtpstart=10000
;rtpend=10200
;rtptimeout=120
;rtpholdtimeout=300
;rtpkeepalive=1
;rtpchecksums=no
;directmedia=no
;canreinvite=no
;
;; SIP Settings
;qualify=yes
;qualifytimeout=2000
;qualifyfreq=30
;registerattempts=0
;registertimeout=0
;session-timers=refuse
;dtmfmode=rfc2833
;maxexpiry=3600
;defaultexpiry=120
;timert1=500
;timerb=32000
;
;; Disable all extra features
;videosupport=no
;textsupport=no
;faxdetect=no
;t38pt_udptl=no
;srvlookup=no
;icesupport=no
;encryption=no
;srtp=no
;progressinband=no




;[1001]
;type=friend
;secret=123
;host=dynamic
;context=default
;nat=force_rport,comedia
;qualify=yes
;qualifyfreq=30
;directmedia=no
;disallow=all
;allow=ulaw
;allow=alaw
;transport=udp
;dtmfmode=rfc2833
;
;[1002]
;type=friend
;secret=123
;host=dynamic
;context=default
;nat=force_rport,comedia
;qualify=yes
;qualifyfreq=30
;directmedia=no
;disallow=all
;allow=ulaw
;allow=alaw
;transport=udp
;dtmfmode=rfc2833
=======
[general]
context=default
bindport=5060
bindaddr=0.0.0.0
allowguest=no
disallow=all
allow=ulaw
allow=alaw

rtcachefriends=yes
rtsaveonregister=yes
rtupdate=yes
ignoreregexpire=yes

nat=force_rport,comedia
qualify=yes
registerattempts=0
registertimeout=0
session-timers=refuse
dtmfmode=rfc2833 
>>>>>>> ee30bdb6c5f2cbe0463f79bd52b5fc80b53677c2
